#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA	02110-1301, USA.
#
#

MALI_CUSTOMER_RELEASE = 1

# Enable this option when running TEM coverage tests
# export GCOV_PROFILE := y

KBASE_PATH = $(src)
PLATFORM_INCLUDE_PATH = $(srctree)/drivers/gpu/arm/exynos/include
PLATFORM_IF_INCLUDE_PATH = $(srctree)/drivers/gpu/arm/exynos/include
PLATFORM_BE_INCLUDE_PATH = $(srctree)/drivers/gpu/arm/exynos/include
PLATFORM_TESTS_INCLUDE_PATH = $(srctree)/drivers/gpu/arm/exynos/include/tests
UAPI_INCLUDE_PATH = $(srctree)/include/uapi/gpu/arm/exynos

ccflags-y += $(DEFINES)
ccflags-y += -I$(PLATFORM_INCLUDE_PATH)
ccflags-y += -I$(PLATFORM_IF_INCLUDE_PATH)
ccflags-y += -I$(PLATFORM_BE_INCLUDE_PATH)
ccflags-y += -I$(PLATFORM_TESTS_INCLUDE_PATH)
ccflags-y += -I$(UAPI_INCLUDE_PATH)

subdir-ccflags-y += $(DEFINES)
subdir-ccflags-y += -I$(PLATFORM_INCLUDE_PATH)
subdir-ccflags-y += -I$(PLATFORM_IF_INCLUDE_PATH)
subdir-ccflags-y += -I$(PLATFORM_BE_INCLUDE_PATH)
subdir-ccflags-y += -I$(PLATFORM_TESTS_INCLUDE_PATH)
subdir-ccflags-y += -I$(UAPI_INCLUDE_PATH)

soc_name := $(shell echo $(CONFIG_EXYNOS_SOC_NAME))

PLATFORM_DIR ?= ../exynos
FRONTEND_DIR := $(PLATFORM_DIR)/frontend
COMMON_DIR := $(PLATFORM_DIR)/common
BACKEND_DIR := $(PLATFORM_DIR)/backend
WA_DIR := $(PLATFORM_DIR)/workarounds
TESTS_DIR := $(PLATFORM_DIR)/tests

$(KBASE_MODULE_NAME)-y += $(PLATFORM_DIR)/mali_exynos_kbase_entrypoint.o

$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_platform.o

ifneq ($(CONFIG_OF), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_platform_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_DEVICETREE), y)
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_devicetree.o
else
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_devicetree_dummy.o
endif

$(KBASE_MODULE_NAME)-y += $(COMMON_DIR)/gpex_utils.o

ifeq ($(CONFIG_MALI_EXYNOS_CLOCK), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_clock.o
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_clock_sysfs.o
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_clock.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_clock_dummy.o
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_clock_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_DVFS), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpu_dvfs_governor.o
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_dvfs.o
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_dvfs_sysfs.o
# TODO: only build this file for SOCs that need it
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_dvfs_external.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_dvfs_dummy.o
endif

ifeq ($(CONFIG_SOC_S5E8825), y)
	TSG_VERSION := _v3
endif

ifeq ($(CONFIG_MALI_TSG), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_tsg$(TSG_VERSION).o
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_tsg_sysfs$(TSG_VERSION).o
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_tsg_external$(TSG_VERSION).o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_tsg_dummy$(TSG_VERSION).o
endif

ifeq ($(TSG_VERSION), _v3)
$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_cmar_sched.o
else
$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_cmar_sched_dummy.o
endif

ifneq (,$(filter y m,$(CONFIG_EXYNOS_CONTENT_PATH_PROTECTION)))
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_smc.o
else
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_smc_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_SECURE_RENDERING_LEGACY), y)
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_secure_legacy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_SECURE_RENDERING_ARM), y)
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_secure.o
endif

ifeq (,$(findstring y, \
	$(CONFIG_MALI_EXYNOS_SECURE_RENDERING_LEGACY) \
	$(CONFIG_MALI_EXYNOS_SECURE_RENDERING_ARM)))
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_secure_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_QOS), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_qos.o
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_qos.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9810) += $(BACKEND_DIR)/gpexbe_qos_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9610) += $(BACKEND_DIR)/gpexbe_qos_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9820) += $(BACKEND_DIR)/gpexbe_qos_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9830) += $(BACKEND_DIR)/gpexbe_qos_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9630) += $(BACKEND_DIR)/gpexbe_qos_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS3830) += $(BACKEND_DIR)/gpexbe_qos_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS2100) += $(BACKEND_DIR)/gpexbe_qos_v3.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_S5E8825) += $(BACKEND_DIR)/gpexbe_qos_v3_8825.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_qos_dummy.o
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_qos_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_BTS_MO), y)
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9810) += $(BACKEND_DIR)/gpexbe_bts_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9820) += $(BACKEND_DIR)/gpexbe_bts_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9610) += $(BACKEND_DIR)/gpexbe_bts_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9830) += $(BACKEND_DIR)/gpexbe_bts_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9630) += $(BACKEND_DIR)/gpexbe_bts_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS3830) += $(BACKEND_DIR)/gpexbe_bts_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS2100) += $(BACKEND_DIR)/gpexbe_bts_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_S5E8825) += $(BACKEND_DIR)/gpexbe_bts_v2.o
else
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_bts_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_DEBUG), y)
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9810) += $(BACKEND_DIR)/gpexbe_debug_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9820) += $(BACKEND_DIR)/gpexbe_debug_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9830) += $(BACKEND_DIR)/gpexbe_debug_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9610) += $(BACKEND_DIR)/gpexbe_debug_v2_9611.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9630) += $(BACKEND_DIR)/gpexbe_debug_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS3830) += $(BACKEND_DIR)/gpexbe_debug_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS2100) += $(BACKEND_DIR)/gpexbe_debug_v3.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_S5E8825) += $(BACKEND_DIR)/gpexbe_debug_v3.o
else
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_debug_dummy.o
endif

$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9810) += $(BACKEND_DIR)/gpexbe_dmabuf_v1.o
$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9820) += $(BACKEND_DIR)/gpexbe_dmabuf_v2.o
$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9830) += $(BACKEND_DIR)/gpexbe_dmabuf_v2.o
$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9610) += $(BACKEND_DIR)/gpexbe_dmabuf_v2.o
$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9630) += $(BACKEND_DIR)/gpexbe_dmabuf_v2.o
$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS3830) += $(BACKEND_DIR)/gpexbe_dmabuf_v2.o
$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS2100) += $(BACKEND_DIR)/dummy/gpexbe_dmabuf_dummy.o
$(KBASE_MODULE_NAME)-$(CONFIG_SOC_S5E8825) += $(BACKEND_DIR)/dummy/gpexbe_dmabuf_dummy.o

ifeq ($(CONFIG_MALI_EXYNOS_LLC), y)
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_llc_coherency.o
else
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_llc_coherency_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_THERMAL), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_thermal.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_thermal_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_GTS), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_gts.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_gts_dummy.o
endif

$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_notifier.o

ifeq (y,$(findstring y,$(CONFIG_KUNIT)$(CONFIG_SEC_KUNIT)))
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_notifier_dummy.o
else
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9810) += $(BACKEND_DIR)/gpexbe_notifier_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9610) += $(BACKEND_DIR)/gpexbe_notifier_v1.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9820) += $(BACKEND_DIR)/gpexbe_notifier_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9830) += $(BACKEND_DIR)/gpexbe_notifier_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9630) += $(BACKEND_DIR)/gpexbe_notifier_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS3830) += $(BACKEND_DIR)/gpexbe_notifier_v2.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS2100) += $(BACKEND_DIR)/gpexbe_notifier_v3.o
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_S5E8825) += $(BACKEND_DIR)/gpexbe_notifier_v3.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_PM), y)
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_pm.o
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_pm.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_pm_dummy.o
	$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/dummy/gpexbe_pm_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_IFPO), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_ifpo.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_ifpo_dummy.o
endif

$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_utilization.o
$(KBASE_MODULE_NAME)-y += $(BACKEND_DIR)/gpexbe_mem_usage.o

ifeq ($(CONFIG_MALI_EXYNOS_UNIT_TESTS), y)
	$(KBASE_MODULE_NAME)-y += $(TESTS_DIR)/runtime_test_runner.o
	$(KBASE_MODULE_NAME)-y += $(TESTS_DIR)/clock_runtime_tests.o
	$(KBASE_MODULE_NAME)-y += $(TESTS_DIR)/pm_state_runtime_tests.o
	$(KBASE_MODULE_NAME)-y += $(TESTS_DIR)/clock_sysfs_tests.o
else
	$(KBASE_MODULE_NAME)-y += $(TESTS_DIR)/runtime_test_runner_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_WAKEUP_CLOCK_WA), y)
	$(KBASE_MODULE_NAME)-$(CONFIG_SOC_EXYNOS9830) += $(WA_DIR)/gpexwa_wakeup_clock_9830.o
else
	$(KBASE_MODULE_NAME)-y += $(WA_DIR)/dummy/gpexwa_wakeup_clock_dummy.o
endif

ifeq ($(CONFIG_MALI_EXYNOS_CL_BOOST), y)
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_clboost.o
else
	$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/dummy/gpex_clboost_dummy.o
endif

$(KBASE_MODULE_NAME)-y += $(FRONTEND_DIR)/gpex_cmar_boost.o

$(KBASE_MODULE_NAME)-$(CONFIG_MALI_SEC_G3D_PEAK_NOTI) += $(WA_DIR)/gpexwa_peak_notify.o
$(KBASE_MODULE_NAME)-$(CONFIG_MALI_EXYNOS_INTERACTIVE_BOOST) += $(WA_DIR)/gpexwa_interactive_boost.o

ifeq ($(CONFIG_MALI_EXYNOS_DEBUG_FAULT_DUMP), y)
	$(KBASE_MODULE_NAME)-y += $(COMMON_DIR)/gpex_debug.o
else
	$(KBASE_MODULE_NAME)-y += $(COMMON_DIR)/dummy/gpex_debug_dummy.o
endif
